name: PaRappa the Rapper 2 (NTSC-J) (July 12th prototype)
sha1: fa7b1d19c68c4d4f06cf3047a05f2b5daaae2a1e
options:
    # paths
    basename: SCPS_150.17
    target_path: iso/SCPS_150.17
    base_path: ..
    
    asm_path: asm
    src_path: src
    build_path: build
    
    extensions_path: tools/splat_ext
    symbol_addrs_path: config/symbol_addrs.txt
    undefined_funcs_auto_path: config/undefined_funcs_auto.txt
    undefined_syms_auto_path:  config/undefined_syms_auto.txt
    
    # compiler 
    compiler: EEGCC
    platform: ps2

    use_gp_rel_macro_nonmatching: False # Disable %gp_rel emission
    make_full_disasm_for_code: True
    ld_bss_contains_common: True
    
    string_encoding: EUC-JP
    rodata_string_guesser_level: 2 # Improve string detection
    disasm_unknown: True
    named_regs_for_c_funcs: False
    gp_value: 0x3a0ef0
    subalign: null
    
    find_file_boundaries: False
    section_order: [".text", ".data", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
segments:
    - [0, databin, elf_header]
    - name: main
      type: code
      start: 0x1000
      vram: 0x100000
      bss_size: 0x18F4434 # Should be 1 byte less?
      subsegments:
        # .text
        - [0x1000,  asm, sdk/crt0]
        - [0x10c8,  asm, sdk/tmp]
        
        - [0x1130,  c, dbug/dbgmsg]
        - [0x1838,  c, dbug/syori]
        - [0x1858,  c, dbug/vramsave]
        
        - [0x24a0,  c, os/mtc]
        - [0x29a0,  c, os/syssub]
        - [0x40a8,  c, os/system]
        - [0x4850,  c, os/cmngifpk]
        - [0x4f68,  c, os/usrmem]
        - [0x5330,  c, os/tim2]

        - [0x6120,  c, main/cdctrl]
        - [0x7d70,  c, main/stdat]
        - [0x7f28,  c, main/scrctrl]
        - [0x10028, c, main/sprite]
        - [0x10980, c, main/fadectrl]
        - [0x10a90, c, main/subt]
        - [0x115e8, c, main/drawctrl]
        - [0x17b70, c, main/effect]
        - [0x19160, c, main/mbar]
        - [0x1ccc8, c, main/pack]
        - [0x1cec0, c, main/etc]
        - [0x1dd58, c, main/wipe]
        - [0x1fce8, c, main/mcctrl]
        - [0x20720, c, main/main]
        - [0x22dc8, c, main/cmnfile]
        - [0x22f68, c, main/p3str]
        - [0x23c50, c, main/commake]

        - [0x24a10, c, menu/menu]
        - [0x24d98, c, menu/menudata]
        - [0x25500, c, menu/menu_mdl]
        - [0x26ec0, c, menu/menusub]
        - [0x38f70, c, menu/p3mc]
        - [0x3bd80, c, menu/memc]
        - [0x3dbf0, c, menu/mntm2hed]
        - [0x3dc08, c, menu/menufont]
        - [0x3ec08, c, menu/pksprite]

        - [0x40db8, c, iop_mdl/wp2cd_rpc]
        - [0x41010, c, iop_mdl/tapctrl_rpc]

        # prlib/nalib
        - [0x41130, cpp, prlib/gifreg]
        - [0x41868, cpp, prlib/model]
          # - [0x41e38, asm, nalib/navector] # Header
        - [0x41e60, cpp, prlib/database]
        # - [0x42078, asm, prlib/objectset] # Header
        - [0x420d8, cpp, prlib/renderstuff]
          # - [0x42650, asm, prlib/renderstuff] # Header
        - [0x42658, cpp, prlib/prlib]
        - [0x430b8, cpp, prlib/setpointer]
        - [0x43820, cpp, prlib/render]
          # - [0x46db0, asm, nalib/navector] # Header
        - [0x471d0, cpp, prlib/renderee] # prlib/renderee
          # - [0x47a08, asm, prlib/renderstuff] # Header
        - [0x47a10, cpp, prlib/transition]
        - [0x47dc8, cpp, prlib/microprogram]
        - [0x47f40, cpp, prlib/spram]
          # - [0x48ce0, asm, nalib/navector] # Header
            # prlib/spram.cpp global constructor
          # - [0x48e38, asm, nalib/navector] # Header
        - [0x49350, cpp, prlib/mfifo]
        - [0x49590, cpp, prlib/spadata]
          # - [0x4a168, asm, nalib/navector] # Header
          # - [0x4bbe0, asm, nalib/navector] # Header
        - [0x4c188, cpp, prlib/scene]
          # - [0x4c988, asm, nalib/navector] # Header
          # - [0x4c9d8, asm, prlib/objectset] # Header
        - [0x4c9f8, cpp, prlib/cluster]
        - [0x4cd18, cpp, prlib/shape]
        - [0x4d200, cpp, prlib/billboard]
          # - [0x4d4e8, asm, nalib/navector] # Header
        - [0x4d8e8, cpp, prlib/depthfield]
          # - [0x4dd38, asm, nalib/napacket] # Header
        - [0x4ddd0, cpp, prlib/vram]
          # - [0x4e668, asm, nalib/napacket] # Header
        - [0x4e8e0, cpp, prlib/random]
        - [0x4ea40, cpp, prlib/menderer]
          # - [0x503b8, asm, nalib/navector] # Header
          # - [0x504c8, asm, nalib/navector] # Header
        - [0x509d0, cpp, prlib/menderercreate]
        - [0x514c8, cpp, prlib/mendererawful]
          # - [0x51ce8, asm, nalib/navector] # Header
        - [0x51d68, cpp, prlib/mendereralpha]
        - [0x52270, cpp, prlib/mendererdata]
          # - [0x52d78, asm, nalib/navector] # Header
        - [0x52e20, cpp, prlib/wave]
        - [0x533f0, cpp, prlib/dmaqueue]
        - [0x53750, cpp, prlib/utility]
        - [0x53790, cpp, prlib/tim2]
        - [0x54840, cpp, prlib/animation]
        - [0x54888, cpp, prlib/camera]
          # - [0x54ad0, asm, nalib/navector] # Header
        - [0x54e80, cpp, prlib/contour]
        - [0x553e8, cpp, prlib/dma]
          # - [0x554a8, asm, nalib/stub_0x554a8]
          # - [0x554a8, asm, nalib/navector] # Header
          # - [0x555d8, asm, nalib/navector]

        - [0x55b58, asm, sdk/graphdev]
        - [0x57af0, asm, sdk/libdma]
        - [0x585c0, asm, sdk/devvu0]
        - [0x589d0, asm, sdk/devvif0]
        - [0x58d00, asm, sdk/libgifpk]
        - [0x59058, asm, sdk/libpad]
        - [0x5a400, asm, sdk/klib]
        - [0x5ac90, asm, sdk/glue]
        - [0x5afc8, asm, sdk/cache]
        - [0x5b248, asm, sdk/intr]
        - [0x5b5a8, asm, sdk/tty]
        - [0x5bac8, asm, sdk/kprintf]
        - [0x5c440, asm, sdk/sifcmd]
        - [0x5cb88, asm, sdk/sifrpc]
        - [0x5dae8, asm, sdk/filestub]
        - [0x61060, asm, sdk/eeloadfile]
        - [0x61dc0, asm, sdk/iopreset]
        - [0x62070, asm, sdk/diei]
        - [0x620d0, asm, sdk/initsys]
        - [0x62140, asm, sdk/thread]
        - [0x624a0, asm, sdk/deci2]
        - [0x62680, asm, sdk/libvu0]
        - [0x633c0, asm, sdk/eecdvd]
        - [0x64b18, asm, sdk/libmc]

        - [0x662d0, asm, sdk/newlib]
        
        # .vutext
        - [0x79040, data, vutext]
        
        # .data
        - [0x7b900, data]
        - [0x7b970, .data, dbug/dbgmsg]
        - [0x7c9e0, data, dbug/vramsave]
        - [0x7ca90, .data, os/mtc]
        - [0x7cb40, .data, os/syssub]
        - [0x7cbc0, .data, os/system]
        - [0x818d8, .data, os/tim2]

        - [0x818f0, data, main/stdat]
        - [0x84258, data, main/scrctrl]
        - [0x85b88, .data, main/fadectrl]
        - [0x85ba0, data, main/subt]
        - [0x86478, data, main/drawctrl]
        - [0x87288, data, main/mbar]
        - [0x87f30, data, main/etc]
        - [0x88000, data, main/wipe]
        - [0x88400, data, main/main]
        - [0x884f0, .data, main/commake]

        - [0x88558, data, menu/menudata]
        - [0x896f8, data, menu/menu_mdl]
        - [0x8c0e0, data, menu/menusub]
        - [0x8ed90, data, menu/p3mc]
        - [0x8edf8, data, menu/memc]
        - [0x8f1d0, data, menu/mntm2hed]
        - [0x90580, data, menu/menufont]
        - [0x91430, data, menu/pksprite]

        - [0x91440, databin, common_ipk] # common_ipk_start/common_ipk_end

        - [0x28d458, data, prlib/database]
        - [0x28d480, data, prlib/renderstuff]
        - [0x28d500, data, prlib/render]
        - [0x28d580, data, prlib/renderee]
        - [0x28d6b0, data, prlib/microprogram]
        - [0x28d710, data, prlib/spram]
        - [0x28d720, data, prlib/scene]
        - [0x28d730, data, prlib/menderer]
        - [0x28d940, data, prlib/mendererawful]
        - [0x28db30, data, prlib/mendereralpha]
        - [0x28dd80, .data, prlib/dma]

        - [0x28ddb0, data, nalib/napacket]
        - [0x28ddc0, data, nalib/navector]
        - [0x28dde0, data, nalib/namatrix]
        
        # .vudata
        - [0x291ed0, data, vudata]
        
        # .rodata
        - [0x291f00, .rodata, dbug/dbgmsg]
        - [0x291f20, .rodata, dbug/vramsave]

        - [0x291fa0, .rodata, os/mtc]
        - [0x291fc0, .rodata, os/syssub]
        - [0x292760, .rodata, os/system]
        - [0x292928, .rodata, os/cmngifpk]
        - [0x292968, .rodata, os/usrmem]
        - [0x292a30, .rodata, os/tim2]

        - [0x292a80, .rodata, main/cdctrl]
        - [0x292da8, .rodata, main/stdat]
        - [0x293a60, .rodata, main/scrctrl]
        - [0x294018, .rodata, main/sprite]
        - [0x294110, .rodata, main/drawctrl]
        - [0x294400, .rodata, main/effect]
        - [0x294430, .rodata, main/mbar]
        - [0x294510, .rodata, main/pack]
        - [0x294530, .rodata, main/etc]
        - [0x294638, .rodata, main/wipe]
        - [0x294748, .rodata, main/mcctrl]
        - [0x294810, .rodata, main/main]
        - [0x294b48, .rodata, main/cmnfile]
        - [0x294b60, .rodata, main/p3str]

        - [0x294c00, .rodata, menu/menudata]
        - [0x296f10, .rodata, menu/menusub]
        - [0x297180, .rodata, menu/p3mc]
        - [0x297650, .rodata, menu/memc]
        - [0x2976e0, .rodata, menu/pksprite]

        - [0x297708, .rodata, iop_mdl/wp2cd_rpc]
        - [0x297728, .rodata, iop_mdl/tapctrl_rpc]

        - [0x297748, .rodata, prlib/gifreg]
        - [0x297770, .rodata, prlib/setpointer]
        - [0x297790, .rodata, prlib/spram]
        - [0x2977a0, .rodata, prlib/spadata]
        - [0x2977e0, .rodata, prlib/menderer]
        - [0x297800, .rodata, prlib/menderercreate]
        - [0x297980, .rodata, prlib/mendereralpha]
        - [0x2979a0, .rodata, prlib/wave]
        - [0x2979b0, .rodata, prlib/tim2]

        - [0x297c10, rodata, sdk/graphdev]
        - [0x298138, rodata, sdk/libdma]
        - [0x298150, rodata, sdk/devvu0]
        - [0x298168, rodata, sdk/libpad]
        - [0x2982c0, rodata, sdk/tty]
        - [0x298330, rodata, sdk/kprintf]
        - [0x298490, rodata, sdk/filestub]
        - [0x298500, rodata, sdk/eeloadfile]
        - [0x298510, rodata, sdk/iopreset]
        - [0x298540, rodata, sdk/thread]
        - [0x298568, rodata, sdk/eecdvd]
        - [0x298780, rodata, sdk/libmc]

        - [0x2987e8, rodata, sdk/newlib]
        
        # # .gcc_except_table
        - [0x299d80, rodatabin, gcc_except_table]

        # .lit4
        - [0x299f00, .lit4, main/cdctrl]
        - [0x299f10, .lit4, main/scrctrl]
        - [0x299f14, lit4] # main/drawctrl
        - [0x299f38, lit4, main/effect]
        - [0x299f40, lit4] # main/mbar

        - [0x299f4c, .lit4, menu/menu_mdl]
        - [0x299f60, lit4] # menu/menusub

        # .sdata
        - [0x29a300, sdata]
        - [0x29a308, .sdata, dbug/vramsave]
        - [0x29a310, .sdata, os/mtc]
        - [0x29a318, .sdata, os/syssub]
        - [0x29a330, sdata, os/system]
        - [0x29a350, .sdata, os/tim2]
        - [0x29a360, .sdata, main/cdctrl]
        - [0x29a378, sdata, main/stdat]
        - [0x29a438, sdata] # main/scrctrl
        #- [0x29a504, sdata] # main/sprite
        #- [0x29a514, sdata] # main/subt
        #- [0x29a518, sdata] # main/drawctrl
        
        - [0x29a5d0, sdata, main/main]
        - [0x29a6e0, .sdata, main/p3str]

        - [0x29a6f0, sdata, menu/menudata]
        - [0x29a700, sdata, menu/menusub]
        - [0x29a830, sdata, menu/p3mc]
        - [0x29a878, sdata, menu/memc]
        - [0x29a890, sdata, menu/menufont]
        - [0x29a8a0, sdata, menu/pksprite]

        - [0x29a8b8, sdata]
        #- [0x29a8b8, sdata, prlib/gifreg]
        #- [0x29a8bc, sdata, prlib/model]
        #- [0x29a8c4, sdata, prlib/database]
        #- [0x29a8c8, sdata, prlib/renderstuff]
        - [0x29a8cc, .sdata, prlib/prlib]
        - [0x29a8e0, sdata] # prlib/render
        - [0x29a940, sdata, prlib/random]
        - [0x29a948, sdata]
        #- [0x29a8ec, sdata]
        
        # - [0x29a9d8, rodatabin] # .sbss / .bss
        
        # .sbss / .bss
        - { start: 0x29aa00, type: sbss,  vram: 0x00399a00, name: dbug/dbgmsg          }
 
        - { start: 0x29aa00, type: .sbss, vram: 0x00399a18, name: os/mtc               }
        - { start: 0x29aa00, type: .sbss, vram: 0x00399a1c, name: os/cmngifpk          }
        - { start: 0x29aa00, type: .sbss, vram: 0x00399a2c, name: os/usrmem            }

        - { start: 0x29aa00, type: .sbss, vram: 0x00399a34, name: main/cdctrl          }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399a38, name: main/scrctrl         }
        - { start: 0x29aa00, type: .sbss, vram: 0x00399a44, name: main/sprite          }
        - { start: 0x29aa00, type: .sbss, vram: 0x00399a48, name: main/subt            }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399a4c, name: main/drawctrl        }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399a80, name: main/mbar            }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399a98, name: main/wipe            }
        - { start: 0x29aa00, type: .sbss, vram: 0x00399aa0, name: main/mcctrl          }
        - { start: 0x29aa00, type: .sbss, vram: 0x00399aac, name: main/p3str           }

        - { start: 0x29aa00, type: .sbss, vram: 0x00399abc, name: menu/menu            }
        - { start: 0x29aa00, type: .sbss, vram: 0x00399ac4, name: menu/menu_mdl        }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399ac8, name: menu/menusub         }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399b60, name: menu/p3mc            }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399b7c, name: menu/menufont        }

        - { start: 0x29aa00, type: sbss,  vram: 0x00399b8c, name: prlib/model          }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399b90, name: prlib/prlib          }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399b94, name: prlib/render         }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399b98, name: prlib/microprogram   }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399ba0, name: prlib/spadata        }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399ba8, name: prlib/menderer       }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399bb4, name: prlib/mendererawful  }
        - { start: 0x29aa00, type: sbss,  vram: 0x00399bc8, name: prlib/wave           }

        - { start: 0x29aa00, type: sbss,  vram: 0x00399bd0, name: sdk/newlib           }

        - { start: 0x29aa1c, type: bss,   vram: 0x00399c00, name: bss                  }

        - { start: 0x29aa1c, type: .bss,  vram: 0x00399d60, name: dbug/dbgmsg          }

        - { start: 0x29aa1c, type: .bss,  vram: 0x003a9d90, name: os/mtc               }
        - { start: 0x29aa1c, type: .bss,  vram: 0x003ba0c0, name: os/syssub            }
        - { start: 0x29aa1c, type: bss,   vram: 0x003babd0, name: os/system            }
        - { start: 0x29aa1c, type: bss,   vram: 0x003dad50, name: os/cmngifpk          }
        - { start: 0x29aa1c, type: bss,   vram: 0x003db380, name: os/usrmem            }
        - { start: 0x29aa1c, type: .bss,  vram: 0x01c5d380, name: os/tim2              }

        - { start: 0x29aa1c, type: bss,   vram: 0x01c5e000, name: main/cdctrl          }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c5f030, name: main/scrctrl         }
        - { start: 0x29aa1c, type: .bss,  vram: 0x01c65b80, name: main/sprite          }
        - { start: 0x29aa1c, type: .bss,  vram: 0x01c6db90, name: main/fadectrl        }
        - { start: 0x29aa1c, type: .bss,  vram: 0x01c6dba0, name: main/subt            }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c6e030, name: main/drawctrl        }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c6fef0, name: main/effect          }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c6ffc0, name: main/mbar            }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c72000, name: main/pack            }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c73018, name: main/etc             }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c730e8, name: main/mcctrl          }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c77630, name: main/main            }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c77640, name: main/p3str           }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c77700, name: main/commake         }

        - { start: 0x29aa1c, type: bss,   vram: 0x01c778c8, name: menu/menu            }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c77a50, name: menu/menusub         }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c81100, name: menu/p3mc            }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c81540, name: menu/memc            }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c81880, name: menu/menufont        }

        - { start: 0x29aa1c, type: .bss,  vram: 0x01c828c0, name: iop_mdl/wp2cd_rpc    }
        - { start: 0x29aa1c, type: .bss,  vram: 0x01c82a00, name: iop_mdl/tapctrl_rpc  }

        - { start: 0x29aa1c, type: bss,   vram: 0x01c82a70, name: prlib/gifreg         }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c83190, name: prlib/prlib          }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c831b0, name: prlib/renderee       }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c831c0, name: prlib/microprogram   }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c831e0, name: prlib/spram          }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c83260, name: prlib/spadata        }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c83390, name: prlib/billboard      }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c833d0, name: prlib/depthfield     }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c833e0, name: prlib/random         }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c83570, name: prlib/menderercreate }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c83ba0, name: prlib/mendererawful  }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c83bd0, name: prlib/mendereralpha  }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c83c10, name: prlib/mendererdata   }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c84c40, name: prlib/wave           }
        - { start: 0x29aa1c, type: bss,   vram: 0x01c884c0, name: prlib/camera         }

        # - { start: 0x29aa1c, type: bss,  vram: 0x01c88500, name: sdk/scelib  }
        # - { start: 0x29aa1c, type: bss,  vram: 0x01c8df00, name: sdk/newlib  }
        
    - [0x29aa00, databin] # pad
    - [0x29b000, databin] # .mfifo
    - [0x2ab000, databin] # .reginfo
    - [0x2ab018, databin] # .mdebug
    - [0x8aaf0d]
